version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_measure_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2019-02-01 to 2020-10-01 by month"
    outputs:
      highly_sensitive:
        measure_data: output/input_measures*.csv

  calculate_measures:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_measures
    needs: [generate_measure_cohort]
    outputs:
      moderately_sensitive:
        measure: output/measure_*_rate.csv

  draw_timeseries:
    run: python:latest python analysis/time_series_plots.py
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        graph: output/event_count_time_series.svg
        tables: output/table_*.csv
