version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_cohort_2017:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2017-01-01 to 2017-12-31 by month"
    outputs:
      highly_sensitive:
        measure_data: output/input_measures*.csv

  generate_cohort_2018:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2018-01-01 to 2018-12-31 by month"
    outputs:
      highly_sensitive:
        measure_data: output/input_measure*.csv

  generate_cohort_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2019-01-01 to 2019-12-31 by month"
    outputs:
      highly_sensitive:
        measure_data: output/input_measur*.csv

  generate_cohort_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2020-01-01 to 2020-12-31 by month"
    outputs:
      highly_sensitive:
        measure_data: output/input_measu*.csv

  generate_cohort_2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2021-01-01 to 2021-02-28 by month"
    outputs:
      highly_sensitive:
        measure_data: output/input_meas*.csv

  calculate_measures:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_measures
    needs: [generate_cohort_2017, generate_cohort_2018, generate_cohort_2019, generate_cohort_2020, generate_cohort_2021]
    outputs:
      moderately_sensitive:
        measure: output/measure_*_rate.csv

  draw_timeseries:
    run: python:latest python analysis/time_series_plots.py
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        graph: output/event_count_time_series.svg
        tables: output/table_*.csv
